[package]
name = "bw-launchpad-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
default-run = "bwl"

[[bin]]
name = "launchpad"
path = "src/main.rs"

[[bin]]
name = "bwl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
cliclack = "0.3.5"
